# Welcome to our Lab Practice!

This lab is about variables, assignments, and their value and data types. Are you ready? Let's get started!

You will find some small tasks in sections below.

## Value assignment

###Task: assign **x** with an int 5. 

Use print() and type() to check the value is correctly assigned, and the data type is correct. For example: print('x:', x, type(x))

In [1]:
# type your code here
x = 5
print("x : ", x, type(x))

x :  5 <class 'int'>

###Task: assign **int_x** with x. 

Use print() and type() to check the value is correctly assigned, and the data type is correct.

In [2]:
# type your code here
int_x = x
print("int_x : ", int_x, type(int_x))

int_x :  5 <class 'int'>

###Task: assign **x** with a float 5.0. 

Use print() and type() to check the value is correctly assigned, and the data type is correct.

In [3]:
# your code will be here
x = 5.0
print("x : ", x, type(x))

x :  5.0 <class 'float'>

###Task: assign **float_x** with x. 

Use print() and type() to check the value is correctly assigned, and the data type is correct.

In [4]:
# your code will be here
float_x = x
print("float_x : ", float_x, type(float_x))

float_x :  5.0 <class 'float'>

###Task: assign **x** with a str '5'. 

Use print() and type() to check the value is correctly assigned, and the data type is correct.

In [5]:
# your code will be here
x = '5'
print("x : ", x, type(x))

x :  5 <class 'str'>

###Task: assign **str1_x** with x. 

Use print() and type() to check the value is correctly assigned, and the data type is correct.

In [6]:
# your code will be here
str1_x = x
print("str_x :" , str1_x, type(str1_x))

str_x : 5 <class 'str'>

###Task: assign **x** with a str '5.0'. 

Use print() and type() to check the value is correctly assigned, and the data type is correct.

In [7]:
# your code will be here
x = '5.0'
print("x : ", x, type(x))

x :  5.0 <class 'str'>

###Task: assign **str2_x** with x. 

Use print() and type() to check the value is correctly assigned, and the data type is correct.

In [8]:
# your code will be here
str2_x = x
print("str_x :" , str1_x, type(str1_x))

str_x : 5 <class 'str'>

###Task: check all variables.

Use print() and type() to check all the variables you created so far: **x, int_x, float_x, str1_x, str2_x** value and data types.

In [13]:
# your code will be here
print(" x : ", x, type(x), "\n", 
      "int_x : ", int_x, type(x), "\n",
      "float_x : ", float_x, type(x), "\n",
      "str1_x : ", str1_x, type(x), "\n",
      "str2_x : ", str2_x, type(x), "\n")

 x :  5.0 <class 'str'>
 int_x :  5 <class 'str'>
 float_x :  5.0 <class 'str'>
 str1_x :  5 <class 'str'>
 str2_x :  5.0 <class 'str'>

## Value converting

For the task below, convert data value from one type to another, assign it to x, and use print() and type() to check for correctness.

###Task: convert a str '0' to int

In [15]:
# your code will be here
num = int("0")
print("num : ", num, type(num))

num :  0 <class 'int'>

###Task: convert a float 0.1 to int

In [18]:
# your code will be here
num1 = 0.1
num1 = int(num1)
print("num1 : ", num1, type(num1))

num1 :  0 <class 'int'>

###Task: convert a str '0' to float

In [19]:
# your code will be here
num3 = float("0")
print("num3 : ", num3, type(num3))

num3 :  0.0 <class 'float'>

###Task: convert an int 0 to float

In [20]:
# your code will be here
num4 = float(0)
print("num4 : ", num4, type(num4))

num4 :  0.0 <class 'float'>

###Task: convert an int 0 to str

In [21]:
# your code will be here
num5 = str(0)
print("num5 : ", num5, type(num5))

num5 :  0 <class 'str'>

###Task: convert a float 0.1 to str

In [22]:
# your code will be here
num6 = str(0.1)
print("num6 : ", num6, type(num6))

num6 :  0.1 <class 'str'>